spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /data-api


taco:
  orders:
    pageSize: 10

logging:
  level:
    taco: DEBUG


